/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "scan.h"

bool_t
xdr_OutputFileScan (XDR *xdrs, OutputFileScan *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->numeroCaratteri))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numeroParole))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->numeroLinee))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_InputDirScan (XDR *xdrs, InputDirScan *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, &objp->nomeDirettorio, 50))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->sogliaDimensione))
		 return FALSE;
	return TRUE;
}
