/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _SCAN_H_RPCGEN
#define _SCAN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct OutputFileScan {
	int numeroCaratteri;
	int numeroParole;
	int numeroLinee;
};
typedef struct OutputFileScan OutputFileScan;

struct InputDirScan {
	char *nomeDirettorio;
	int sogliaDimensione;
};
typedef struct InputDirScan InputDirScan;

#define REMOTESCAN 0x20000020
#define REMOTESCANVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define FILE_SCAN 1
extern  OutputFileScan * file_scan_1(char **, CLIENT *);
extern  OutputFileScan * file_scan_1_svc(char **, struct svc_req *);
#define DIR_SCAN 2
extern  int * dir_scan_1(InputDirScan *, CLIENT *);
extern  int * dir_scan_1_svc(InputDirScan *, struct svc_req *);
extern int remotescan_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define FILE_SCAN 1
extern  OutputFileScan * file_scan_1();
extern  OutputFileScan * file_scan_1_svc();
#define DIR_SCAN 2
extern  int * dir_scan_1();
extern  int * dir_scan_1_svc();
extern int remotescan_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_OutputFileScan (XDR *, OutputFileScan*);
extern  bool_t xdr_InputDirScan (XDR *, InputDirScan*);

#else /* K&R C */
extern bool_t xdr_OutputFileScan ();
extern bool_t xdr_InputDirScan ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_SCAN_H_RPCGEN */
